### ISSUE TITLE
Xcode 8 cocoapods 1.0.1(1.1.0beta2也有该问题) 引入 JSPatchPlatform 会导致 xcode codesign 错误

### ISSUE THREAD

**Issue by davidfuzju** [bang590/JSPatchPlatform#1]
前几天引入了新的 JSPatchPlatform SDK 的 Pod，然后就发现工程在进行真机调试时，build 成功后始终报报错, 如图:

![2016-09-21 at 15 15](https://cloud.githubusercontent.com/assets/3890843/18701260/50c3ea6c-800e-11e6-9673-15864f58776e.png)

最后发现当在最新版的 Xcode 使用 cocoa pods 1.0.1(后升级为1.1.0beta2也有同样的问题)引入
JSPatchPlatform SDK 1.6.1 后，就会出现该问题，无论是使用 xcode 的 auto manage signing 还是 manual 都无法正确签名 build 到真机。

目前通过 pod 安装的 AFNetworking 的 target 的 signing 如下

![2016-09-21 at 15 18](https://cloud.githubusercontent.com/assets/3890843/18701381/dad66432-800e-11e6-995f-79ce6b30421a.png)

我自己猜测可能 JSPatchPlatform 中的 signing 可能设置了具体信息，导致 Xcode 在签名阶段在本地寻找一个不存在的 provisioning profile 文件。

希望能有帮助

**Comment by davidfuzju** [comment]
似乎只有 1.6.1 有这个问题，我退回了版本就好了

**Comment by bang590** [comment]
已解决，等待pod缓存更新，现在可以通过指定git解决：
`pod 'JSPatchPlatform', :git => 'https://github.com/bang590/JSPatchPlatform.git'`

**Comment by davidfuzju** [comment]
😁，好的。花了我两天时间...
