### ISSUE TITLE
  pod 'JSPatchPlatform', :git => 'https://github.com/bang590/JSPatchPlatform.git'用该命令pod安装后运行报错！

### ISSUE THREAD

**Issue by liuluchang** [bang590/JSPatchPlatform#4]
ndefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_JSPatch", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
报错如下，该如何修改呢？不想手动引入，cocoapod如何安装？pod search JSPatchPlatform显示无结果

**Comment by bang590** [comment]
先确定pod是官方源，`pod repo update`

**Comment by liuluchang** [comment]
好滴，我update试一哈，多谢！手动引入集成已经搞定
