### ISSUE TITLE
下载脚本成功，加载找不到脚本！

### ISSUE THREAD

**Issue by MemoryReload** [bang590/JSPatchPlatform#6]
按照JSPatchPlatform官方的教程配置了项目，本地测试了脚本main.js可用。在JSPatchPlatform上传脚本之后，启动项目，从日志可以看到脚本已经下载，但是，在下载完之后尝试重新加载新的脚本时，找不到脚本文件！输出信息如下图：
![console_log](https://user-images.githubusercontent.com/6024370/29503333-5c82f5c0-8669-11e7-8cee-edbd8e36ec56.jpg)
在app的目录下并未找到下载成功的脚本文件，个人怀疑框架中是否将文件下载之后解密再保存？由于解密失败，所以指定的脚本目录下没有文件，造成加载的时候找不到更新的脚本文件。希望提供更详细的输出日志，无法定位问题的所在。

**Comment by bang590** [comment]
这个确实奇怪，解密失败是会有log的，再更新一次也不行吗？

**Comment by MemoryReload** [comment]
I Have tried for dozens of times. Then I come here for help. :)

**Comment by MemoryReload** [comment]
@bang590 I Have tried for dozens of times. Then I come here for help. :)

**Comment by zhangbo** [comment]
已经知道了。是版本的问题呢。如果使用1.7.x就可以了。

**Comment by MemoryReload** [comment]
@zhangbo 可是，我是用git clone的啊……难道不是master的代码？😨

**Comment by MemoryReload** [comment]
@zhangbo  我再次看了下代码，master最后一次提交也只到1.6.6，在哪里找到1.7.x的代码？请赐教。

**Comment by bang590** [comment]
@MemoryReload 可邮件索取，见平台公告

**Comment by MemoryReload** [comment]
@bang590 刚刚去官网看了下，看到公告了。谢谢～   建议在gitHub上也注明这个吧，不然还会有很多人遇到这个问题。也就是，后面的1.7.x的代码，已经不再向gitHub推送，不再开源了呗。

**Comment by bang590** [comment]
这个项目只用于pod，平台SDK之前也并不是开源的，现在只是未公开更新到pod。

**Comment by MemoryReload** [comment]
@bang590 JSPatchCore是开源的吧，只是脚本分发平台的代码是闭源的。不管怎样，经历了这么久总算找到原因了，谢谢。
